# -*- coding: utf-8 -*-

schedule_config = {
    'survey_schedule': [
        'TaskConfig',
        {
            'id': "check_address",
            'title': "Vérifier l'adresse",
            'default_assigned_user': 'survey',
            'creation_state': 'validating_address',
            'starting_states': 'validating_address',
            'ending_states': ('waiting_address', 'procedure_choice',),
            'start_date': 'urban.start_date.deposit_date',
            'additional_delay': 2,
        },
        {
            'id': "assign_temporary_address",
            'title': "Assigner une adresse temporaire",
            'default_assigned_user': 'survey',
            'creation_state': 'waiting_address',
            'starting_states': 'waiting_address',
            'ending_states': ('procedure_choice',),
            'start_date': 'urban.start_date.deposit_date',
            'additional_delay': 2,
        },
    ],
    'opinions_schedule': [
        'TaskConfig',
        {
            'id': "ask_road_opinion",
            'title': "Avis voirie",
            'default_assigned_group': 'Voirie_editors',
            'default_assigned_user': 'road_editor',
            'creation_state': 'creation',
            'creation_conditions': ('liege.urban.schedule.is_internal_opinion',),
            'starting_states': 'waiting_opinion',
            'ending_states': ('opinions_given',),
            'start_date': 'liege.urban.asking_date',
            'additional_delay': 15,
        },
        'TaskConfig',
        {
            'id': "ask_sssp_opinion",
            'title': "Avis SSSP",
            'default_assigned_group': 'SSSP_editors',
            'default_assigned_user': 'sssp_editor',
            'creation_state': 'creation',
            'creation_conditions': ('liege.urban.schedule.is_internal_opinion',),
            'starting_states': 'waiting_opinion',
            'ending_states': ('opinions_given',),
            'start_date': 'liege.urban.asking_date',
            'additional_delay': 15,
        },
    ],
    'buildlicence': [
        'TaskConfig',
        {
            'id': "accuse",
            'title': 'Accusé de réception',
            'default_assigned_user': 'imio.schedule.assign_current_user',
            'creation_state': 'in_progress',
            'starting_states': ('in_progress',),
            'ending_states': ('accepted',),
            'due_date_computation': 'urban.start_date.deposit_date',
            'additional_delay': 10,
        },
        {
            'id': "depot",
            'title': 'Dépôt dossiers',
            'default_assigned_user': 'imio.schedule.assign_current_user',
            'creation_state': 'in_progress',
            'starting_states': ('in_progress',),
            'ending_states': ('accepted',),
            'due_date_computation': 'urban.start_date.deposit_date',
            'additional_delay': 10,
        },
        {
            'id': "analyse",
            'title': 'Dossiers à analyser',
            'default_assigned_user': 'imio.schedule.assign_current_user',
            'starting_state': 'accepted',
            'ending_states': ('refused',),
            'due_date_computation': 'urban.start_date.deposit_date',
            'additional_delay': 10,
        },
    ],

}
